version: '3.8'

services:
  exchange-service:
    container_name: exchange-service
    hostname: exchange-service
    image: selanandrew/selivanov-exchange-service:latest
    ports:
      - "8080:8080"
    environment:
      RATE_ADAPTER_URL: http://fx-rates-api-adapter:8081/fx-rates-api
      DATABASE_URL: "jdbc:postgresql://capacity-plan-postgres:5432/capacity_plan_db"
      DATABASE_USER: "exchange-db-username"
      DATABASE_PASS: "exchange-db-password"

  fx-rates-api-adapter:
    container_name: fx-rates-api-adapter
    hostname: fx-rates-api-adapter
    image: selanandrew/selivanov-fx-rates-api-adapter:latest
    ports:
      - "8081:8081"
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "exchange-db"
      POSTGRES_USER: "exchange-db-username"
      POSTGRES_PASSWORD: "exchange-db-password"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  # metrics
  grafana:
    image: grafana/grafana:10.1.9
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

#logs

#todo

volumes:
  grafana_data:
  pg-data: