version: '3.8'

services:
  exchange-service:
    container_name: exchange-service
    hostname: exchange-service
    image: selanandrew/selivanov-exchange-service:latest
    ports:
      - "8080:8080"
    environment:
      RATE_ADAPTER_URL: http://host.docker.internal:8081/fx-rates-api
      DATABASE_URL: "jdbc:postgresql://postgres:5432/exchange-db"
      DATABASE_USER: "exchange-db-username"
      DATABASE_PASS: "exchange-db-password"

  fx-rates-api-adapter:
    container_name: fx-rates-api-adapter
    hostname: fx-rates-api-adapter
    image: selanandrew/selivanov-fx-rates-api-adapter:latest
    ports:
      - "8081:8080"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "exchange-db"
      POSTGRES_USER: "exchange-db-username"
      POSTGRES_PASSWORD: "exchange-db-password"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d


  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    command:
      - start-dev
    environment:
      #      KEYCLOAK_DATABASE_VENDOR: postgress
      #      KEYCLOAK_DATABASE_HOST: "host.docker.internal"
      #      KC_DB_URL: "jdbc:postgresql://host.docker.internal:5432/exchange-db"
      #      KC_DB_USERNAME: "exchange-db-username"
      #      KC_DB_PASSWORD: "exchange-db-password"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8484:8080"
  #    depends_on:
  #      - postgres
  #    links:
  #      - "postgres:postgres"

  # metrics
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./devops_configs/prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.1.9
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  elk:
    image: sebp/elk
    volumes:
      - ./devops_configs/elk/tcp-input.conf:/etc/logstash/conf.d/tcp-input.conf
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5045:5045"
#logs

#todo

volumes:
  grafana_data:
  pg-data: