server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

adapter:
  client:
    rate-adapter:
      url: ${RATE_ADAPTER_URL:http://localhost:8081/fx-rates-api}

spring:
  jpa:
    show-sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/exchange-db}
    username: ${DATABASE_USER:exchange-db-username}
    password: ${DATABASE_PASS:exchange-db-password}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.yaml
    enabled: true

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: exchangeServiceId
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8484/realms/bank_realm
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8484/realms/bank_realm


#keycloak:
#  auth-server-url: http://localhost:8484
#  realm: test_realm
#  resource: exchange
#  ssl-required: NONE
#  credentials:
#    secret: aXakJDhJBp2nmtgfjXbWJfYfajXiWdr3
##  bearer-only: true

spring.security.oauth2.client.registration.keycloak.client-id: ${CLIENT_ID:login-app}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.keycloak.scope: openid
spring.security.oauth2.client.provider.keycloak.issuer-uri: ${ISSUER_URI:http://localhost:8484/realms/SpringBootKeycloak}
spring.security.oauth2.client.provider.keycloak.user-name-attribute: preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri: ${ISSUER_URI:http://localhost:8484/realms/SpringBootKeycloak}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: INFO

logbook:
  predicate:
    exclude:
      - path: /health
      - path: /prometheus
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret