server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

adapter:
  client:
    exchange-rate-adapter:
      url: "http://localhost:8081"

spring:
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.yaml
    enabled: true

logbook:
  predicate:
    exclude:
      - path: /health
      - path: /prometheus
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret