server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

adapter:
  client:
    rate-adapter:
      url: ${RATE_ADAPTER_URL:http://localhost:8081/fx-rates-api}

spring:
  jpa:
    show-sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/exchange-db}
    username: ${DATABASE_USER:exchange-db-username}
    password: ${DATABASE_PASS:exchange-db-password}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.yaml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logbook:
  predicate:
    exclude:
      - path: /health
      - path: /prometheus
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret