server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

adapter:
  client:
    fx-rates:
      url: "https://api.fxratesapi.com"
      api-key: "fxr_live_caae3d32b9d16deaa1b898fdc43d3e23b7d6"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    org.zalando.logbook: TRACE


logbook:
  predicate:
    exclude:
      - path: /health
      - path: /prometheus

  format.style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
