name: CI/CD pipeline


on:
  push:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: gradle  bootJar
#      - name: Run tests with Gradle
#        run: ./gradlew test

      # docker build
      - name: Build exchange-service image
        run: docker build . --file exchange-service/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-exchange-service:latest
      - name: Build exchange-rate-adapter image
        run: docker build . --file fx-rates-api-adapter/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest

      # docker push to yandex registry
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push exchange-service image to yandex registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/selivanov-exchange-service:latest
      - name: Push fx-rates-api-adapter image to yandex registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest

      # docker push to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag exchange-service image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/selivanov-exchange-service:latest
      - name: Tag exchange-rate-adapter image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/selivanov-fx-rates-api-adapter:latest