name: CI/CD pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew bootJar
  #      - name: Run tests with Gradle
  #        run: ./gradlew test

  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build exchange-service image
        run: docker build . --file exchange-service/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/exchange-service:latest
      - name: Build exchange-rate-adapter image
        run: docker build . --file exchange-rate-adapter/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/exchange-rate-adapter:latest
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push exchange-service image
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/exchange-service:latest
      - name: Push exchange-rate-adapter image
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/exchange-rate-adapter:latest