name: CI/CD pipeline


on:
  push:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Выкачивание исходников
      - uses: actions/setup-java@v4 # скачивание джавы
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: gradle  bootJar
#      - name: Run tests with Gradle
#        run: ./gradlew test

      # docker build
      - name: Build exchange-service image
        run: docker build . --file exchange-service/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-exchange-service:latest
      - name: Build exchange-rate-adapter image
        run: docker build . --file fx-rates-api-adapter/Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest

      # docker push to yandex registry
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push exchange-service image to yandex registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/selivanov-exchange-service:latest
      - name: Push fx-rates-api-adapter image to yandex registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest

      # docker push to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag exchange-service image
        run: docker tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-exchange-service:latest ${{ secrets.DOCKER_USERNAME }}/selivanov-exchange-service:latest
      - name: Tag exchange-rate-adapter image
        run: docker tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest ${{ secrets.DOCKER_USERNAME }}/selivanov-fx-rates-api-adapter:latest

      - name: Push exchange-service image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/selivanov-exchange-service:latest
      - name: Push exchange-rate-adapter image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/selivanov-fx-rates-api-adapter:latest

  deploy:
    name: deploy-yandex-cloud
    runs-on: ubuntu-latest
    needs: [ build-test-push ]
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1 # плагин
        with:
          # параметры деплоя
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          # пуш с контейнер регистри
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/selivanov-fx-rates-api-adapter:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-cores: 1
          revision-memory: 1024Mb

